[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_saver = "4TmUvjfZaNx2b6Ma8gedmKaGXgfaHmmR9TwZUtJjSNq4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gabrielrojas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
