[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol-token-saver = "BxRivoj1QuavXdB6buPEitCqQnBE8kfpCiwKdhMx4cEx"
sol_saver = "8L6PYBgDY1XC64VN6qeDrJtVp6titb2eE6Biaxkinooy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/gabrielrojas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
